ccflags-y += -Idrivers/media/platform/msm/camera/cam_utils
ccflags-y += -Iinclude/soc/oppo
ccflags-y += -Idrivers/input/misc/oppo_face_drivers/include
KBUILD_CFLAGS += -DOPPO_MX6300_TEE_SUPPORT
obj-y += mx6300-spi.o

