#/************************************************************************************
#** Copyright (C), 2016-2020, OPPO Mobile Comm Corp., Ltd
#** All rights reserved.
#**
#** VENDOR_EDIT
#**
#** Description: -
#**      add for max989xx driver
#**
#**
#** --------------------------- Revision History: --------------------------------
#** <author>                                  <data>    <version >  <desc>
#** ------------------------------------------------------------------------------
#** Jianfeng.Qiu@Swdp.Multimedia  2017/01/10   1.0          create file
#** Zhaoan.Xu@PSW.MM.AudioDriver  2018/01/06   1.1          modified file for module build
#** ------------------------------------------------------------------------------
#**
#************************************************************************************/

snd-soc-max989xx-objs := max98927.o
obj-$(CONFIG_SND_SOC_MAX98928) += snd-soc-max989xx.o
