
snd-soc-ia6xx-objs := ia6xx-iacore.o iacore.o \
			iacore-cdev.o iacore-vs.o \
			iacore-fsm.o iacore-raw.o \
			iacore-pm.o ia6xx-i2s.o \
			iacore-uart.o iacore-uart-common.o

obj-$(CONFIG_SND_SOC_IA6XX)	+= snd-soc-ia6xx.o
