ifeq ($(CONFIG_OPPO_CHARGER_MTK6763)_$(CONFIG_OPPO_CHARGER_MTK6771),n_n)
obj-y	+= oppo_pic16f.o
endif
ifeq ($(CONFIG_OPPO_CHARGER_MTK6771),y)
obj-y	+= oppo_n76e.o
endif

obj-y	+= oppo_vooc_fw.o
obj-y	+= oppo_stm8s.o
